- key:               telos-testnet
  name:              Telos Testnet
  client:            telos                                   # API client name.
  server:            http://127.0.0.1:8888                 # Public Telos node endpoint.
  height:            30818213                              # Initial block number from which sync will be started.
  min_confirmations: 20                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://telos-test.eosx.io/account/#{address}
    transaction:     https://telos-test.eosx.io/transaction/#{txid}
  status:            active
