- id:                     telos
  name:                   TLOS
  blockchain_key:         telos-testnet
  symbol:                 'T'
  type:                   coin
  precision:              4
  base_factor:            100_000_000
  enabled:                true
  # Deposits with less amount are skipped during blockchain synchronization.
  # We advise to set value 10 times bigger than the network fee to prevent losses.
  min_deposit_amount:     0.0001
  min_collection_amount:  0.0001
  withdraw_limit_24h:     100.0
  withdraw_limit_72h:     500.0
  deposit_fee:            0
  withdraw_fee:           0
  position:               1
  options:
    #NOT OPTIONAL
    telos_token_name: "TLOS"